version: '3.7'
services:
  node:
    container_name: enriquegil-me-vue
    image: node:lts-alpine
    user: node
    command: sh -c "npm install && npm run serve"
    volumes:
    - ./../..:/srv
    working_dir: /srv
    ports:
    - 8080:8080

